version: '3'

services:

  db_test:
    image: postgres:latest
    container_name: db_test
    environment:
      POSTGRES_USER: ${TEST_DB_USER}
      POSTGRES_PASSWORD: ${TEST_DB_PASSWORD}
      POSTGRES_DB: ${TEST_DB_NAME}
    ports:
      - ${TEST_DB_PORT}:5432
    env_file:
      - ./.env
